### ISSUE TITLE
Documentation for setup

### ISSUE THREAD

**Issue by kf107** [JettIsOnTheNet/Micropython-Examples-for-ESP32-Cheap-Yellow-Display#1]
Thank you for this repository, @JettIsOnTheNet . I  wrote an article documenting how I got your repo to work on my CYD, which I thought might be useful to others:

https://kf106.medium.com/how-to-use-micropython-on-a-cyd-cheap-yellow-display-e158d5e4a2e7

**Comment by JettIsOnTheNet** [comment]
Hey. Thank you very much. I appreciate that. I will update the docs and also link back to your article and credit you for that in the morning. Unless you would like to fork, update and create a pull req for the credit, I will do. Cheers.

**Comment by JettIsOnTheNet** [comment]
Thank you. This has been resolved in 59c6184e18eda158d55dfa5a303f74cbb2d43868 and 1e06cd857eeec9cd737ce80ed4d9faedceba5f77. Now marked closed.
