### ISSUE TITLE
XglcdFont's glitched rendering

### ISSUE THREAD

**Issue by mvsteen** [JettIsOnTheNet/Micropython-Examples-for-ESP32-Cheap-Yellow-Display#2]
Hi, using your library, and a spun off version specifically for the CYD variant i have (2.4 capacitive touch with USB C). all the display draw functions work great...except XglcdFont usage. I do not know if the XglcdFont class returns faulty objects or if the draw_text and draw_letter functions are the issue.

It does not matter if I use glcd fonts found online or ones created with the tool, the rendering is always messed up (like a jumbled random image)

There seems to be some interpretation fault, and being new to microcontroller coding (my experience is with creating programs and scripts automating SolidWorks, a CAD program) I have zero idea how to  proceed because I cannot be certain if the error is with me or with the library method.

**Comment by JettIsOnTheNet** [comment]
A spun off version? Can you give me more information to debug this please? More in depth hardware information, debugging logs, a copy of the font, photos etc
