### ISSUE TITLE
ili4193.py - color565(r,g,b) plays wrong colors

### ISSUE THREAD

**Issue by chriskuku** [JettIsOnTheNet/Micropython-Examples-for-ESP32-Cheap-Yellow-Display#4]
I found out, that the following code works (for my cyd2usb):
(b and r have to be swapped in the parameter list)
There my be a different place where to repair this.

```py
def color565(b, g, r):
    """Return RGB565 color value.

    Args:
        r (int): Red value.
        g (int): Green value.
        b (int): Blue value.
    """ 
    return (r & 0xf8) << 8 | (g & 0xfc) << 3 | b >> 3

```

**Comment by JettIsOnTheNet** [comment]
This is down to the version of CYD you have. There are different producers of CYD, or use different components. Sadly they don't all follow the same pinouts etc. It can take a little bit of playing around to get it to work.
